### ISSUE TITLE
Failover support

### ISSUE THREAD

**Issue by stna1981** [nemosminer/DSTM-equihash-miner#2]
Hi,

I really like this miner, good results on Pascal cards, better than EWBF, and easy to use. However, what really lacks is a failover support. In case the mail pool is down, the miner cannot operate properly any longer. Switching to an alternative pool would therefore be a really useful feature.

Any plans for that in the near future?

Best regards

Stefan

**Comment by cdrw700** [comment]
Watch this : https://github.com/Undertrey/FarmWatchBot
